### ISSUE TITLE
Cannot use object of type supercool\tools\fields\data\WidthData as array in Craft 3.3

### ISSUE THREAD

**Issue by louderthan10** [spicywebau/tools#20]
Hi, I _think_ this is a Tools issue and not SuperTable, but let me know if I'm wrong.

I'm using the Width field inside of a SuperTable field on a multi-site install. After I change the propagation method on the SuperTable field (since Craft 3.3), I can no longer save my entries and get the following error:

```
Error: Cannot use object of type supercool\tools\fields\data\WidthData as array in /Users/trav/Websites/louderthanten/vendor/supercool/tools/src/fields/data/WidthData.php:134
Stack trace:
#0 /Users/trav/Websites/louderthanten/vendor/supercool/tools/src/fields/Width.php(136): supercool\tools\fields\data\WidthData->setData(Array, Object(supercool\tools\fields\data\WidthData))
#1 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/base/Element.php(2270): supercool\tools\fields\Width->normalizeValue(Object(supercool\tools\fields\data\WidthData), Object(verbb\supertable\elements\SuperTableBlockElement))
#2 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/base/Element.php(896): craft\base\Element->normalizeFieldValue('grid')
#3 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/validators/Validator.php(254): craft\base\Element->__get('grid')
#4 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(verbb\supertable\elements\SuperTableBlockElement), Array)
#5 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(1832): yii\base\Model->validate()
#6 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(2073): craft\services\Elements->_saveElementInternal(Object(verbb\supertable\elements\SuperTableBlockElement), true, false)
#7 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(1950): craft\services\Elements->_propagateElement(Object(verbb\supertable\elements\SuperTableBlockElement), false, Array)
#8 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(488): craft\services\Elements->_saveElementInternal(Object(verbb\supertable\elements\SuperTableBlockElement), false, true)
#9 /Users/trav/Websites/louderthanten/vendor/verbb/super-table/src/services/SuperTableService.php(771): craft\services\Elements->saveElement(Object(verbb\supertable\elements\SuperTableBlockElement), false)
#10 /Users/trav/Websites/louderthanten/vendor/verbb/super-table/src/fields/SuperTableField.php(857): verbb\supertable\services\SuperTableService->saveField(Object(verbb\supertable\fields\SuperTableField), Object(benf\neo\elements\Block))
#11 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/base/Element.php(2139): verbb\supertable\fields\SuperTableField->afterElementPropagate(Object(benf\neo\elements\Block), false)
#12 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(1957): craft\base\Element->afterPropagate(false)
#13 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(488): craft\services\Elements->_saveElementInternal(Object(benf\neo\elements\Block), false, true)
#14 /Users/trav/Websites/louderthanten/vendor/spicyweb/craft-neo/src/services/Fields.php(200): craft\services\Elements->saveElement(Object(benf\neo\elements\Block), false)
#15 /Users/trav/Websites/louderthanten/vendor/spicyweb/craft-neo/src/Field.php(687): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry))
#16 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/base/Element.php(2139): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), false)
#17 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/elements/Entry.php(1248): craft\base\Element->afterPropagate(false)
#18 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(1957): craft\elements\Entry->afterPropagate(false)
#19 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Elements.php(488): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true)
#20 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/controllers/EntriesController.php(378): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#21 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#22 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-entry', Array)
#25 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#26 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entries/save-en...', Array)
#27 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('entries/save-en...', Array)
#28 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#29 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /Users/trav/Websites/louderthanten/public/index.php(21): yii\base\Application->run()
#31 /Users/trav/.composer/vendor/laravel/valet/server.php(158): require('/Users/trav/Web...')
#32 {main}

```

Also getting this in the Queue log:

```
2019-08-28 15:14:57 - error - craft\queue\QueueLogBehavior::afterError
 [323494] Resaving supertable blocks (attempt: 1) - Error (time: 1.721s): Cannot use object of type supercool\tools\fields\data\WidthData as array
2019-08-28 15:14:57 - error - Error
Error: Cannot use object of type supercool\tools\fields\data\WidthData as array in /vendor/supercool/tools/src/fields/data/WidthData.php:134

```

Tools version: 2.1.8
Craft version: 3.3.0.1
SuperTable version: 2.2.1
Multisite: yes

**Comment by ttempleton** [comment]
Looks like this should be fixed as of version 2.2.2 (https://github.com/spicywebau/tools/commit/c6283b99f51bedd6b3ee38b14f5c19376bfb6a28).
